### ISSUE TITLE
Symbols function definition is void : compat-executable-find

### ISSUE THREAD

**Issue by ThibaultGH** [emacs-compat/compat#11]
Hi,

After updating to the latest version of compat with `M-x package-reinstall RET compat` I've got a strange annoying behavior that when trying to open a file for the first time in the emacs session I have a message below the mode-line saying : 
`Symbols function definition is void : compat-executable-find` (screenshot message below mode-line)
![message_below_mode-line](https://user-images.githubusercontent.com/43775782/211269059-a8707b29-2f32-476c-91d6-4797178df49e.png)

And it does not open the file, then when tried a second time, it does open the file but seems to miss loading the appropriate modes for clear reading of colors and lines. (See the screenshot fails_launch_mode)
![fails_launch_mode](https://user-images.githubusercontent.com/43775782/211269357-50ba81ae-80ab-4b6b-ac3c-bd63832115c0.png)

**Comment by minad** [comment]
Update Compat to 29.1.1.0

**Comment by ThibaultGH** [comment]
> Update Compat to 29.1.1.0. Make sure that you restart Emacs. If all of this doesn't work, reset your package repository and reinstall everything. If the problem still persists, can you provide a stack trace for the issue (void function), since this will then point to the broken package causing the issue?

It is version 29.1.1.0 I think, according to this buffer at least : 
![compat_29_1_1_0](https://user-images.githubusercontent.com/43775782/211283523-d763bd5c-c9ad-479b-8822-18e86e36a748.png)

I also did a `M-: RET (byte-recompile-directory package-user-dir nil 'force)` to recompile all the packages.

And the problem persist ! So now, provide stack trace.

Here is the thing, I've got a weird behavior with this error since while it is prompt below the mode-line, I cant see it in the *messages* buffer or any *warning* buffer. I can run `emacs -debug-init`  but it doesnt give me anything. So don't really know how to give you a stack trace of the error and find the package that would be broken.

We can meet on System Crafters' discord if ever you're willing to solve this way faster and come up with a clean solution asap. It'll help, cause I'm no expert in elisp and package management ^^'
System Crafers' discord : https://discord.gg/Ft6FbDpH

**Comment by minad** [comment]
You could just grep for compat-executable-find in your Emacs directory. Then you should find the culprit. Maybe your Magit version is outdated. Didn't you update all packages?

**Comment by ThibaultGH** [comment]
> You could just grep for compat-executable-find in your Emacs directory. Then you should find the culprit. Maybe your Magit version is outdated. Didn't you update all packages?

Yes it's the problem, I had several packages that would not update because of this specific error and kept giving me `Symbols function definition is void : compat-executable-find `. So I added auto-package-update in my init.el to try to get those packages to upgrade. It seems that I managed to get them upgraded, but I now have a new issue saying : 
`Error (use-package): doom-modeline/:init: Symbol’s function definition is void: doom-modeline-mode`

In the list-package given by package.el, I have a doom-modeline whose status is `dependency`  dated 11/11/2022 and another one which is `obsolete` dated 01/07/2023 so if I understand things right, there is an previous version of doom-modeline that is outdated so depricated and mark as obsolete, and a newer one whose status is dependency that I don't understand really cause I do have `(use-package doom-modeline)` set up in my init.el
