### ISSUE TITLE
Please consider adding `setopt` to compat-29

### ISSUE THREAD

**Issue by ktetzlaff** [emacs-compat/compat#12]
Emacs 29 added `setopt` (which internally uses `setopt--set`) to `cus-edit.el`. Please add `setopt` to compat.

**Comment by minad** [comment]
> Emacs 29 added |setopt| (which internally uses |setopt--set|) to
> |cus-edit.el|. Please add |setopt| to compat.

Yes, we can add this to compat. But I don't consider it of high
importance given that the function is not useful for package authors.
