### ISSUE TITLE
executable-find

### ISSUE THREAD

**Issue by DSMasterson** [emacs-compat/compat#14]
Early in trying to figure this out (newbie to debugging), but...

Compat-29 seems to break executable-find for a lot of things.  My Emacs (27.1) just now auto-package-update just updated some packages and that brought in some dependencies after which things started breaking with 'executable-find' errors ("Symbol's value as a variable is void: executable-find").  I think the latest magit requires compat-29.1.1.0 and that started the ball rolling.

I've rolled back compat and magit for the time being and stopped auto-package-update.

**Comment by DSMasterson** [comment]
Nevermind.  I found the discussion in magit/magit and package-reinstall of magit and compat seem to have fixed things.

Closing.

**Comment by aspiers** [comment]
I had this too.  Not sure which discussion you are referring to?  It would be helpful to include a link to save others from having to hunt for the same info :-)

In any case, I found the following:

- #11
- https://github.com/magit/magit/issues/4841
- https://github.com/magit/magit/issues/4836

What seems to have worked for me is upgrading compat, magit, forge to the latest, making sure they were all recompiled to avoid outdated `.elc` files, and then restarting emacs.

**Comment by aspiers** [comment]
Another gotcha I forgot to mention: it seems several repos (including magit and forge) have switched from `master` to `main`.  My local checkouts of these repos were still on `master`, so they were not picking up bug-fixes relating to this problem.  Until I fixed that, the problems remained.

**Comment by kngwyu** [comment]
> My local checkouts of these repos were still on master, so they were not picking up bug-fixes relating to this problem. Until I fixed that, the problems remained.

I exactly got the same problem 😅  
I updated magit by `straight-pull-package`, but actually, I needed to checkout to main
