### ISSUE TITLE
Idea: linter support?

### ISSUE THREAD

**Issue by jdtsmith** [emacs-compat/compat#17]
Just getting into compat.  One thing that would be awesome is if `emacs-lint` or some other linter could read the `Package-Requires`, check the min version of emacs (& compat?), and then provide information on which function/macro calls need (or no longer need) to be invoked with `compat-call`.  Probably that would mean exporting this information into some data structure. 

Not sure if that's a crazy idea, but it would be a wonderful way to check on compat usage.  And then, once you bump your emacs min-version, keep things up to date.

**Comment by minad** [comment]
See https://github.com/purcell/package-lint/issues/227 and https://github.com/purcell/package-lint/issues/100

**Comment by jdtsmith** [comment]
You're always one step ahead ;).  Put a note of support over there.
