### ISSUE TITLE
FEATURE REQUEST: Add support for Emacs major version 30

### ISSUE THREAD

**Issue by rswgnu** [emacs-compat/compat#18]
I am using a pre-release/development version of Emacs numbered 30.0.50 for testing.  It seems vertico does a (require 'compat) which fails since the compat package only presently supports through major version 29.

You could say that compat is not needed with the latest major Emacs version but then packages couldn't require it in this case, so it seems an update is needed, if I am interpreting the error correctly.  Things seem to work properly when I use compat on Emacs 27.1 for example.

**Comment by minad** [comment]
There should not be any problem due to compat on 30. Can you be more specific about your issue? See https://github.com/minad/consult#bug-reports.

**Comment by rswgnu** [comment]
You are right.  Previously, I had 2 elpa versions of compat installed,
compat-28 and compat-29.  I interactively deleted the compat-28 one in the
package manager but a cached version of the path to that library still
existed in my load-path when I restarted Emacs and the path to compat-29
did not for some reason, so compat failed to load.
