### ISSUE TITLE
compat-function being a macro

### ISSUE THREAD

**Issue by phikal** [emacs-compat/compat#21]
What is the reason for `compat-function` to be a macro instead of a function?  Could it being a macro lead to issue if the fboundp check fails at macro-expansion time?

**Comment by minad** [comment]
On 3/19/23 11:17, Philip wrote:
> What is the reason for |compat-function| to be a macro instead of a
> function? Could it being a macro lead to issue if the fboundp check
> fails at macro-expansion time?

The idea is that the Compat function resolution is performed at compile
time for efficiency reasons. The fboundp check should not fail at
compile time, since the byte code compiler will load the functions of
the libraries which have been required.
