### ISSUE TITLE
Providing `loaddefs-generate`

### ISSUE THREAD

**Issue by phikal** [emacs-compat/compat#23]
This could be useful as part of adding package.el to ELPA.  NEWS.29 says:

```
+++
** "loaddefs.el" generation has been reimplemented.
The various "loaddefs.el" files in the Emacs tree (which contain
information about autoloads, built-in packages and package prefixes)
used to be generated by functions in autoloads.el.  These are now
generated by loaddefs-gen.el instead.  This leads to functionally
equivalent "loaddefs.el" files, but they do not use exactly the same
syntax, so using 'M-x update-file-autoloads' no longer works.  (This
didn't work well in most files in the past, either, but it will now
signal an error in any file.)

In addition, files are scanned in a slightly different way.
Previously, ';;;###' specs inside a top-level form (i.e., something
like '(when ... ;;;### ...)' would be ignored.  They are now parsed as
usual.
```

Does this sound doable?  The easiest approach would be to reduce this to `make-directory-autoloads`, but edge-cases might be a problem.  Concerns I have are:

- If any Lisp file binds `generated-autoload-file' as a file-local variable, write its autoloads into the specified file instead,
- The point about specs inside of a top-level form from above,
- Proper handling of custom cookies (`;;;###foo-autoload`).

**Comment by minad** [comment]
On 4/7/23 16:21, Philip wrote:
> Does this sound doable? The easiest approach would be to reduce this to
> |make-directory-autoloads|, but edge-cases might be a problem. Concerns
> I have are:
> 
>   * If any Lisp file binds `generated-autoload-file' as a file-local
>     variable, write its autoloads into the specified file instead,
>   * The point about specs inside of a top-level form from above,
>   * Proper handling of custom cookies (|;;;###foo-autoload|).

I don't know enough about these limitations, but if we can reduce
`loaddefs-generate` to `make-directory-autoloads`, we should do that. It
hopefully works in most relevant cases. Another (maybe better) option
might be to distribute the entire loaddefs-gen.el together with
package.el as part of the ELPA package "package".

**Comment by minad** [comment]
It seems the [discussion](https://lists.gnu.org/archive/html/emacs-devel/2023-04/msg00252.html) converged to using `make-directory-autoloads` on older Emacs versions. I think this is a good decision since autoload generation seems to be pretty much an "internal" feature of the package manager.

Btw, I added `native-comp-available-p`, see https://github.com/emacs-compat/compat/commit/81c5046b3118323d756eaed6a521846cc1361fb5.
