### ISSUE TITLE
Add `copy-tree` from master

### ISSUE THREAD

**Issue by josephmturner** [emacs-compat/compat#24]
Hello! Thank you for this package!!!

[This patch](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=63509) was merged two days ago onto master, changing the behavior of `copy-tree`.

I was going to submit a PR adding a new `compat-defun`, but I noticed there is no `compat-30.el`.

What do you suggest?

**Comment by phikal** [comment]
We can start working on compat-30, but I suggest that be done in a seperate branch.  If you want to prepare the patch, I can create the empty file and set up the infrastructure.

**Comment by minad** [comment]
It is maybe a little bit early to start working on compat-30, but there is nothing wrong with collecting new functionality in a separate branch as Philip suggested.

**Comment by josephmturner** [comment]
Since #25 was merged into the emacs-30 branch, I'll close this.
