### ISSUE TITLE
Add reasonable treesit functions

### ISSUE THREAD

**Issue by snogge** [emacs-compat/compat#33]
It would be useful to have at least `treesit-available-p`, `treesit-language-available-p`, and `treesit-ready-p` in `compat`. They can all just return `nil`.  Maybe `treesit-parser-create` too?

Adding `defvar`s for some of the common variables such as `treesit-font-lock-feature-list`, `treesit-font-lock-setttings`, `treesit-range-settings`, `treesit-language-source-alist`, ....   could make byte compilation warning free.

**Comment by minad** [comment]
Thanks for the proposal. Can you please describe your use case? This will help us find a good solution, maybe one which doesn't require changes in Compat.

If your package relies on tree sitter, I assume it necessarily also has to depend on Emacs 29.1? So in which scenarios would such treesit definitions help? It seems a bit out of scope of Compat to add many stubs without any real functionality. Adding these definitions only to avoid byte compilation errors is a bit out of proportion.

**Comment by snogge** [comment]
I'm just experimenting with adding tree sitter support to one of my packages.  I hope to eventually merge my nascent `bitbake-ts-mode` with my existing `bitbake-mode` and use `treesit-available-p` and `treesit-language-available-p` to determine which way to go for syntax highlighting and all the other good stuff that tree sitter provides. 
Whether I manage to combine the two modes or not, I will still provide both modes in one package, which means I do not want to require Emacs 29.1.  Having `treesit-available-p` available through compat means writing
```elisp
(when (treesit-available-p)
   ....
)
```
instead of 
```elisp
(when (and (fboundp 'treesit-available-p) 
           (treesit-available-p 'bitbake))
  ...
)
```
Having just the `treesit-*available-p` functions returning `nil` could make that a lot cleaner.
The rest of my issue is probably nice-to-have, but the having does-emacs-have-this-lib functions like `treesit-available-p` and `libxml-available-p` in compat makes sense to me.

**Comment by minad** [comment]
> Whether I manage to combine the two modes or not, I will still provide both modes in one package, which means I do not want to require Emacs 29.1. Having treesit-available-p available through compat means writing

Thanks, I see. Creating such dual major modes with two ways of operation is a possible use case.

However the current trend seems to be that all modes are duplicated, e.g., python-mode and python-ts-mode. Ooth this design is not finalized upstream. Base modes are discussed and Emacs 30 will come with an extra mode derivation mechanism.

If you end up keeping the two modes, maybe reconsider creating two separate packages?

> Having just the treesit-*available-p functions returning nil could make that a lot cleaner.

I am not convinced that your code will be significantly better if we provide only treesit-available-p, while you still have to write a large list of treesit-* defvars to avoid byte compilation warnings. You save the fboundp check in the conditions but this is only a small win.

For now I prefer if we don't add any treesitter-related stubs to Compat. It is not obvious where to draw a line for the reasonable feature set of Compat. We document a [few limitations](https://elpa.gnu.org/packages/doc/compat.html#Limitations) in the manual. One limitation, which applies to treesitter, is that we cannot port back functionality which relies on deep changes in the C core.

We also have to keep maintainability and overall package size in mind. Given that treesitter is out of scope, it is cleaner to keep this subsystem completely out of Compat for now. We will revisit this question at some point I guess. Maybe we will see some abstraction layers upstream which make it easier to patch over the rift between treesitter and non-treesitter modes.
