### ISSUE TITLE
Byte-compiling compat-2.\\.el files fails 

### ISSUE THREAD

**Issue by dr-scsi** [emacs-compat/compat#34]
I have compat-29.1.4.4 installed from ELPA and with this recipe:

- `emacs -Q`
- `M-x package-initialize RET`
- `M-x package-recompile RET compat RET`

I get:

```
Compiling file /path/to/.emacs.d/elpa/compat-29.1.4.4/compat-25.el at Fri ...
Entering directory ‘/path/to/.emacs.d/elpa/compat-29.1.4.4/’
compat-25.el:24:2: Error: Cannot open load file: No such file or directory, compat-macs.el

Compiling file /path/to/.emacs.d/elpa/compat-29.1.4.4/compat-26.el at Fri ...
compat-26.el:24:2: Error: Cannot open load file: No such file or directory, compat-macs.el

Compiling file /path/to/.emacs.d/elpa/compat-29.1.4.4/compat-27.el at Fri  ...
compat-27.el:24:2: Error: Cannot open load file: No such file or directory, compat-macs.el

Compiling file /path/to/.emacs.d/elpa/compat-29.1.4.4/compat-28.el at Fri ...
compat-28.el:24:2: Error: Cannot open load file: No such file or directory, compat-macs.el

Compiling file /path/to/.emacs.d/elpa/compat-29.1.4.4/compat-29.el at Fri ...
compat-29.el:24:2: Error: Cannot open load file: No such file or directory, compat-macs.el
```

which means that the `compat-2.\\.el` files are not byte-compiled.  Is this an issue or am I missing something?  TIA.

**Comment by minad** [comment]
Do you use Emacs 30? A stub of compat.el got recently added to Emacs itself, see https://github.com/emacs-mirror/emacs/commit/db195116a4279521e9cf03c52b7026032461e3e1. Therefore you can simply `package-delete` Compat and things should continue to work. If you use an older Emacs version, I would still recommend to remove Compat and install it again.

**Comment by dr-scsi** [comment]
Yes, I'm running Emacs 30, and I've missed the fact that a `compat.el` was added to the core.  So I uninstalled compat for now, problem solved `;-)` I'm closing this issue.  Thanks for your response 👍
