### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by seagle0128** [emacs-compat/compat#35]
Since `seq` is updated to 2.24, I got some error in CI. Please update the dependencies to the latest version accordingly. Thanks!

```
Missing dependency: "Failed to verify signature: \"seq-2.24.tar.sig\"", "Setting `package-selected-packages' temporarily since \"emacs -q\" would overwrite customizations"
```

**Comment by phikal** [comment]
seq 2.23 is the version that Emacs 29.1 [bundles](https://git.savannah.gnu.org/cgit/emacs.git/tree/lisp/emacs-lisp/seq.el?h=emacs-29.1#n7) (and the current version of Compat still indicates that it provides compatibility up to 29.1), so it would be more consistent to stick to that.

The problem you are experiencing is related to a signing error on ELPA, you should report that upstream.

**Comment by minad** [comment]
As Philip mentioned, seq 2.23 is bundled with 29.1. There is also no strong reason to depend on a newer version, since Compat doesn't use newer seq features.
