### ISSUE TITLE
** New polymorphic comparison function 'value<'.

### ISSUE THREAD

**Issue by phikal** [emacs-compat/compat#36]
We need to add the built-in function:

> This function returns non-nil if the first argument is less than the
> second.  It works for any two values of the same type with reasonable
> ordering for numbers, strings, symbols, bool-vectors, markers, buffers
> and processes.  Conses, lists, vectors and records are ordered
> lexicographically.
> It is intended as a convenient ordering predicate for sorting, and is
> likely to be faster than hand-written Lisp functions.

**Comment by phikal** [comment]
I can implement the function over the next few days and add some tests, also as a means to get back into Compat development.

**Comment by minad** [comment]
Added in 8190769d9eb9258dd8361bd322d90228dc586770.

**Comment by phikal** [comment]
How regrettable, I wrote a version of this function this morning but didn't have the time to push it: a7fb705b93e2d289e0e10656942fcfc02ff7cd15.  Perhaps we can merge the tests?

**Comment by minad** [comment]
Yes, feel free to add more tests. I believe we can also move tests over from Emacs master. I haven't done that so far. My tests are written by hand.

However note that I have still open questions about value<, see https://github.com/emacs-compat/compat/commit/38aba13d75a049b03bedefb06101a77f5b78b0e2. Therefore I didn't want to stall this any longer. Eli plans to stabilize Emacs 30 pretty soon I've heard.
