### ISSUE TITLE
** New 'sort' arguments and features.

### ISSUE THREAD

**Issue by phikal** [emacs-compat/compat#37]
Sort has also been updated:

    The 'sort' function can now be called using the signature

	(sort SEQ &rest KEYWORD-ARGUMENTS)

    where arguments after the first are keyword/value pairs, all optional:
    ':key' specifies a function that produces the sorting key from an element,
    ':lessp' specifies the ordering predicate, defaulting to 'value<',
    ':reverse' is used to reverse the sorting order,
    ':in-place is used for in-place sorting, as the default is now to
    sort a copy of the input.

    The new signature is less error-prone and reduces the need to write
    ordering predicates by hand.  We recommend that you use the ':key'
    argument instead of ':lessp' unless a suitable ordering predicate is
    already available.  This can also be used for multi-key sorting:

	(sort seq :key (lambda (x) (list (age x) (size x) (cost x))))

    sorts by the return value of 'age', then by 'size', then by 'cost'.

    The old signature, '(sort SEQ PREDICATE)', can still be used and sorts
    its input in-place as before.

(And yes, I know that it is annoying that the signature has changed)

**Comment by minad** [comment]
I am aware of this addition. The new sort and #36 are on my todo list, but it would be great if you have the bandwidth to work on it.

**Comment by minad** [comment]
@phikal Btw, Mattias posted some compatibility code for sort on the Emacs bug tracker. We can use it in a compat-defun with :extended=t, such that the new function can be called via compat-call.

**Comment by minad** [comment]
Added in 8190769d9eb9258dd8361bd322d90228dc586770.
