### ISSUE TITLE
** 'defvar-keymap' can specify hints for 'repeat-mode'.

### ISSUE THREAD

**Issue by phikal** [emacs-compat/compat#38]
This will probably need some separate support for both Emacs 29 and pre-29 releases.  Or should we the prefixed definition just reduce to an un-prefixed defvar-keymap expression?

    Using ':repeat (:hints ((command . "hint") ...))' will show
    the hint string in the echo area together with repeatable keys.

**Comment by minad** [comment]
This sounds like a feature which we do not have to implement, since it is an acceptable downgrade of functionality if the hints are not shown?

**Comment by minad** [comment]
Closing this issue as per my previous comment.
