### ISSUE TITLE
`get-buffer-create` and `generate-new-buffer` optional `INHIBIT-BUFFER-HOOKS` argument

### ISSUE THREAD

**Issue by josephmturner** [emacs-compat/compat#42]
Would it be appropriate for `compat` to support `(compat-call generate-new-buffer "foo" t)`?

Thank you!

cc @alphapapa

**Comment by minad** [comment]
When was this argument introduced? We can maybe emulate it by temporarily let-binding `buffer-list-update-hook`, `kill-buffer-hook` and `kill-buffer-query-functions` to nil, such that the hooks do not run. But maybe there are problematic side effects of doing that.

**Comment by phikal** [comment]
Joseph Turner ***@***.***> writes:

> Would it be appropriate for `compat` to support `(compat-call generate-new-buffer "foo" t)`?

The function was first added in 27.1, but isn't listed in compat-27 so
it should be added without a prefix anyway.

But generally, this is about the INHIBIT-BUFFER-HOOKS argument, right?
For the record, this enables:

       Both functions accept an optional argument INHIBIT-BUFFER-HOOKS.  If
    it is non-‘nil’, the buffer they create does not run the hooks
    ‘kill-buffer-hook’, ‘kill-buffer-query-functions’ (*note Killing
    Buffers::), and ‘buffer-list-update-hook’ (*note Buffer List::).  This
    avoids slowing down internal or temporary buffers that are never
    presented to users or passed on to other applications.

Unless I am missing something, this sets the `inhibit_buffer_hooks'
bit-field in `struct buffer_text`, which we cannot directly access from
Elisp -- but was added with 27.1 anyway.

So the question is if we can emulate the above behaviour, e.g. by
re-binding the mentioned hooks to empty hooks?  Or would that have
unintended side-effects?

> Thank you!

> cc @alphapapa

-- 
	Philip Kaludercic on peregrine

**Comment by minad** [comment]
> The function was first added in 27.1, but isn't listed in compat-27 so
it should be added without a prefix anyway.

No, this is not correct. `generate-new-buffer` exists already in Emacs 24. See:
https://github.com/emacs-mirror/emacs/blob/a27ae9d7650a1230d4359eaf0a949f827315a6d2/lisp/subr.el#L3193

>  Both functions accept an optional argument INHIBIT-BUFFER-HOOKS.  If
    it is non-‘nil’, the buffer they create does not run the hooks
    ‘kill-buffer-hook’, ‘kill-buffer-query-functions’ (*note Killing
    Buffers::), and ‘buffer-list-update-hook’ (*note Buffer List::). 

Yes. I've just confirmed the list by grepping the Emacs source for inhibit_buffer_hooks. These three hooks are affected and nothing else.

> Unless I am missing something, this sets the `inhibit_buffer_hooks'
bit-field in `struct buffer_text`, which we cannot directly access from
Elisp -- but was added with 27.1 anyway.

Indeed. We cannot access it.

> So the question is if we can emulate the above behaviour, e.g. by
re-binding the mentioned hooks to empty hooks?  Or would that have
unintended side-effects?

Yes, that's my question. It will probably work. The main problem with variable bindings is that they will also shadow variable modifications. If one locally binds hooks to nil, newly added hooks will not get added. This matters for example with lazy loading of packages, if one tries to inhibit mode hooks that way. I don't think such problems can happen here however.

**Comment by josephmturner** [comment]
Is https://github.com/emacs-compat/compat/pull/43 what you have in mind?

According to the `28.1` news:

```
** Buffers can now be created with certain hooks disabled.
The functions 'get-buffer-create' and 'generate-new-buffer' accept a
new optional argument INHIBIT-BUFFER-HOOKS.  If non-nil, the new
buffer does not run the hooks 'kill-buffer-hook',
'kill-buffer-query-functions', and 'buffer-list-update-hook'.  This
avoids slowing down internal or temporary buffers that are never
presented to users or passed on to other applications.
```

While `kill-buffer-hook` and `kill-buffer-query-functions` were introduced before `24`, `buffer-list-update-hook` appears to have been introduced in `28.1`, at least according to its `*Help*` buffer:

```
  This variable may be risky if used as a file-local variable.
  Probably introduced at or before Emacs version 28.1.
```

I'm curious to better understand what you mean by this @minad:

> The main problem with variable bindings is that they will also shadow variable modifications. If one locally binds hooks to nil, newly added hooks will not get added. This matters for example with lazy loading of packages, if one tries to inhibit mode hooks that way. I don't think such problems can happen here however.

Thank you!

**Comment by phikal** [comment]
> No, this is not correct. generate-new-buffer exists already in Emacs 24

My bad, I only tracked it back to f1d9e41ab022358c5086227d5b267f3f35d27666 where it was moved from files.el to subr.el.

**Comment by minad** [comment]
Let's continue the discussion in https://github.com/emacs-compat/compat/pull/43.

**Comment by josephmturner** [comment]
I am not sure that it is possible to add this feature to `compat`. `let`-binding the hooks to nil as in the proposed patch doesn't work because the `let` bindings only apply during the call to `get-buffer-create`.  However, the expected behavior is that the three global hooks will not be run when the buffer is created or killed.  For this, we could perhaps modify each existing function in each hook to do nothing if the buffer being created, renamed, or killed, etc. is the current buffer.

Already this is too complex, and we haven't accounted for new functions added to any of these hooks after the call to `get-buffer-create`.
