### ISSUE TITLE
New feature of display-buffer

### ISSUE THREAD

**Issue by astoff** [emacs-compat/compat#53]
I'm not sure this is in scope of compat, but `display-comint-buffer-action` is now obsolete and one is supposed to replace `(display-buffer BUFFER display-comint-buffer-action)` with `(display-buffer BUFFER '(nil (category . comint)))`. 

The `category` action argument seems to be a new feature in Emacs 30.

**Comment by minad** [comment]
Hi Augusto! This feature seems out of scope. I don't think it is easily possible to add the `category` action argument in an easy way to the existing `display-buffer` infrastructure without replicating a lot of brittle code, which will be hard to maintain in the long run. The window management is also particularly intricate from what I've seen. To clarify the scope a bit better - Compat can easily provide isolated and self-contained new APIs to Emacs. See the recent additions as examples or the new Emacs 31 `with-work-buffer`. Everything else must be decided on a case by case basis, however the more isolated and self-contained the better. So in cases where we an existing complex API is extended, the answer tends to be that the extension is out of scope.

**Comment by astoff** [comment]
Makes sense, I just thought I'd check anyway.
