### ISSUE TITLE
Emacs 28.1 `seq-union`

### ISSUE THREAD

**Issue by tschwinge** [emacs-compat/compat#54]
I'm running into an error: `aset: Symbol’s function definition is void: seq-union`.  `seq-union`, <https://www.gnu.org/software/emacs/manual/html_node/elisp/Sequence-Functions.html#index-seq_002dunion>, is new in Emacs 28.1, <https://www.gnu.org/savannah-checkouts/gnu/emacs/news/NEWS.28.1>:

```
** New function 'seq-union'.
This function takes two sequences and returns a list of all elements
that appear in either of them, with no two elements that compare equal
appearing in the result.
```

Would this be appropriate to support in `compat-28.el`?

**Comment by bbatsov** [comment]
My bad - the functions are actually there. I'm assuming the real problem is something to do with the load order if you're using a version of Emacs that bundles `seq.el` and have a package depending on `seq.el`.

**Comment by phikal** [comment]
Bozhidar Batsov ***@***.***> writes:

> bbatsov left a comment (emacs-compat/compat#54)
>
> My bad - the functions are actually there. I'm assuming the real
> problem is something to do with the load order if you're using a
> version of Emacs that bundles `seq.el` and have a package depending on
> `seq.el`.

Did you install seq from ELPA using package.el?  If so, this is a
package.el bug (which might or might not have been fixed, depending on
the version of Emacs that you are using).  I guess a lazy way out of the
issue could be to add

  (require 'seq-25 nil t)

to "force" loading the newer version, assuming that you don't support
Emacs 24 anymore.
