### ISSUE TITLE
semicolon shadows ending parenthesis

### ISSUE THREAD

**Issue by erusyd** [emacs-compat/compat#9]
In compat-tests.el, line 254: 
 (should-equal (key-parse "C-;") [?\C-;])

**Comment by minad** [comment]
Not an issue, test suite is green

**Comment by doolio** [comment]
> Not an issue

Are you sure? It seems to prevent `straight` from building the package. I get the following error.

> Building no-littering...
> Building no-littering → Building compat...
> autoload-generate-file-autoloads: ../../../../../../../.emacs.d/straight/build/compat/compat-tests.el:0:0: error: scan-error: (Unbalanced parentheses 9333 92132)

**Comment by minad** [comment]
I see. This means there is a bug in the autoload generator. Furthermore there issue that straight ignores .elpaignore. Note that compat-tests.el is NOT part of the package.

We should probably escape the semicolon somehow. Is the issue fixed if you write \C-\; instead?

Furthermore compat-tests.el could be moved to a test directory. Then straight would not compile it, right? Otoh compiling it may also be beneficial to uncover issues like this.

**Comment by doolio** [comment]
Firstly, thank you for the quick response.

> Is the issue fixed if you write ?\C-\; instead?

Yes, this fixes the issue.

> Furthermore compat-tests.el could be moved to a test directory. Then straight would not compile it, right?

Perhaps, but I'm not sure. If it matters it did not compile the compat-mac.el file but it did for all the other .el files.

**Comment by minad** [comment]
compat-macs.el is intentionally not compiled. This file is only needed at compile time.

**Comment by doolio** [comment]
Ah ok.
